- README.md
- docs/pages/basic_usage.rst
- galois/__init__.py
- galois/conversion.py
- galois/gf.py
- galois/gf2m.py
- galois/poly.py
- tests/fields/test_properties.py
- tests/polys/test_instantiation.py
- tests/polys/test_operations.py
> Add constructors to Poly class

- galois/__init__.py
- galois/poly.py
- galois/prime.py
- tests/fields/test_constructors.py
- tests/fields/test_instantiation.py
- tests/helper.py
- tests/polys/test_constructors.py
- tests/polys/test_function.py
- tests/polys/test_operations.py
- tests/test_primes.py
> Add tests for polynomial irreducibility

- .github/workflows/release.yml
- README.md
- docs/_templates/module.rst
- galois/__init__.py
- galois/algorithm.py
- galois/array.py
- galois/conway.py
- galois/factor.py
- galois/gf.py
- galois/gf_prime.py
- galois/linalg.py
- galois/math_.py
- galois/meta_gf2.py
- galois/meta_gf2m.py
- galois/meta_gfp.py
- galois/meta_gfpm.py
- galois/meta_mixin_ufunc.py
- galois/modular.py
- galois/poly.py
- galois/poly_functions.py
- galois/prime.py
- setup.cfg
- tests/fields/test_arithmetic_exceptions.py
- tests/fields/test_numpy_ufuncs.py
- tests/polys/test_function.py
- tests/test_algorithms.py
- tests/test_factor.py
- tests/test_math.py
- tests/test_primes.py
This pull request includes many performance speed-ups, mostly optimizing how numba is used.
> Additional numba optimizations

- galois/_polys/_poly.py
- tests/polys/test_operations.py
> Add __len__ method

- galois/_fields/_calculate.py
- setup.cfg
> Support newer Numba/NumPy versions

- galois/_polys/_poly.py
- tests/polys/test_operations.py
Implement the proposal discussed in https://github.com/mhostetter/galois/issues/193#issuecomment-991929455. This PR should resolve suggestions from #193 and #197.
> Add `Poly.coefficients()` method accessor

- galois/_polys/_factor.py
- galois/_polys/_poly.py
- tests/polys/test_constructors.py
> Ensure `Poly.Degrees` has unique degree inputs

- galois/_fields/_main.py
- tests/fields/test_characteristic_poly.py
Adds #220.
```python
In [1]: import galois                                                                                                            
In [2]: import numpy as np                                                                                                       
In [3]: GF = galois.GF(3**5)                                                                                                     
In [4]: A = GF.Random((3,3)); A                                                                                                  
Out[4]: 
GF([[ 80,  32,   8],
[115, 145, 102],
[175,  89,  70]], order=3^5)
In [5]: poly = A.characteristic_poly(); poly                                                                                     
Out[5]: Poly(x^3 + 188x^2 + 25x + 12, GF(3^5))
In …
```
> Compute characteristic poly of square matrices

- README.md
- docs/api/polys.rst
- galois/_fields/_poly_functions.py
- tests/polys/test_lagrange_poly.py
- tests/polys/test_minimal_polys.py
```python
In [1]: import galois                                                                                                            
In [2]: GF = galois.GF(2**8)                                                                                                     
In [3]: x = GF.Random(10); x                                                                                                     
Out[3]: GF([ 14,  79, 129, 131, 122, 115,  39, 140, 106, 162], order=2^8)
In [4]: y = GF.Random(x.shape); y                                                                                                
Out[4]: GF([245,  94,  86, 167, 147, 147, 239,  43, 183, 130], order=2^8)
In [5]: L = galois.lagrange_poly(x, y); L …
```
> Add `galois.lagrange_poly()`

- requirements-min.txt
> Add missing dependency to min-requirements.txt

- galois/_fields/_calculate.py
- galois/_fields/_functions.py
- galois/_fields/_gf2m.py
- galois/_fields/_gfp.py
- galois/_fields/_gfpm.py
- galois/_fields/_lookup.py
- galois/_fields/_main.py
References:
* #178 
* #226 
* https://github.com/numba/numba/issues/7802
> Resolve `NumbaIRAssumptionWarning`

- galois/_fields/_functions.py
- galois/_fields/_main.py
- galois/_modular.py
- galois/_ntt.py
- galois/_prime.py
- requirements-dev.txt
- tests/fields/test_properties.py
- tests/test_ntt.py
- JIT compile the NTT algorithm
- Add the radix-2 Cooley-Tukey algorithm
> JIT compile NTT

- docs/requirements.txt
See https://github.com/jbms/sphinx-immaterial/issues/131
> Fix search in `dirhtml` docs builds

- galois/_codes/_bch.py
- galois/_codes/_reed_solomon.py
- tests/codes/test_bch.py
- tests/codes/test_rs.py
This is more consistent with other properties, eg `is_primitive` and `is_narrow_sense`.
> Rename `systematic` FEC property to `is_systematic`

- docs/basic-usage/array-arithmetic.rst
- galois/_domains/_calculate.py
- galois/_domains/_lookup.py
- galois/_domains/_ufunc.py
- galois/_fields/_array.py
- tests/fields/test_arithmetic.py
```python
In [1]: GF = galois.GF(3**5, display="poly")
In [2]: alpha = GF.primitive_element; alpha
Out[2]: GF(α, order=3^5)
In [3]: x = GF.Random(10, low=1); x
Out[3]: 
GF([              α^2 + α + 1,              α^2 + 2α + 2,
2α^4 + 2α^3 + 2α,   α^4 + α^3 + α^2 + α + 1,
2α^4 + 2α^2 + 2,     α^4 + 2α^3 + 2α^2 + 1,
2α^4 + 2α^3 + 1,   α^4 + α^3 + α^2 + α + 2,
2α^3 + 2α^2 + 1, 2α^4 + α^3 + 2α^2 + α + 2], order=3^5)
In [4]: i = x.log(); i
Out[4]: array([ 10, 222, 107,  64,  27, 154, 240, 117, 109,  53])
In [5]: np.array_equal(alpha ** i, x)
Out[5]: True
```
```python
In [7]: beta = GF.primitive_elements[-1]; beta
Out[7]: GF(2α^4 + 2α^3 + 2α^2 + 2α + 2, order=3^5)
In [8]: i = x.log(beta); i
Out[8]: array([ 72,  98, 117, 122,  25,  44,  34, 189,  83,  67])
In [9]: np.array_equal(beta ** i, x) …
```
> Generalized logarithm

- .github/workflows/build.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- README.md
- docs/conf.py
- src/galois/typing.py
This PR builds the docs and pushes to GitHub pages on pushes to `master` and official releases. See https://mhostetter.github.io/galois/v0.1.0/.
> Deploy to GitHub pages

- .github/workflows/build.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
> Upgrade GitHub Actions for deprecations

- src/galois/_codes/_bch.py
- src/galois/_codes/_cyclic.py
- src/galois/_codes/_linear.py
- src/galois/_codes/_reed_solomon.py
- tests/codes/conftest.py
> Add `output` kwarg to FEC `encode()` and `decode()` methods

- docs/basic-usage/array-classes.rst
- src/galois/_fields/_factory.py
- tests/fields/test_factory.py
```python
In [2]: GF = galois.GF(2**100); print(GF.properties)
Galois Field:
name: GF(2^100)
characteristic: 2
degree: 100
order: 1267650600228229401496703205376
irreducible_poly: x^100 + x^57 + x^56 + x^55 + x^52 + x^48 + x^47 + x^46 + x^45 + x^44 + x^43 + x^41 + x^37 + x^36 + x^35 + x^34 + x^31 + x^30 + x^27 + x^25 + x^24 + x^22 + x^20 + x^19 
+ x^16 + x^15 + x^11 + x^9 + x^8 + x^6 + x^5 + x^3 + 1
is_primitive_poly: True
primitive_element: x
In [3]: GF = galois.GF(2, 100); print(GF.properties)
Galois Field:
name: GF(2^100)
characteristic: 2
degree: 100
order: 1267650600228229401496703205376
irreducible_poly: x^100 + x^57 + x^56 + x^55 + x^52 + x^48 + x^47 + x^46 + x^45 + x^44 + x^43 + x^41 + x^37 + x^36 + x^35 + x^34 + x^31 + x^30 + x^27 + x^25 + x^24 + x^22 + x^20 …
```
> Add new `galois.GF(p, m)` call signature

- src/galois/_prime.py
```python
In [2]: %time galois.perfect_power(2**471)
CPU times: user 3.03 s, sys: 0 ns, total: 3.03 s
Wall time: 3.03 s
Out[5]: (2, 471)
In [3]: %time galois.perfect_power(2**571)
```
```python
In [2]: %time galois.perfect_power(2**471)
CPU times: user 7 µs, sys: 14 µs, total: 21 µs
Wall time: 23.8 µs
Out[2]: (2, 471)
In [3]: %time galois.perfect_power(2**571)
CPU times: user 25 µs, sys: 0 ns, total: 25 µs
Wall time: 26.5 µs
Out[3]: (2, 571)
```
> Speed-up factoring powers of small primes

- pyproject.toml
> Add support for NumPy 1.25

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- docs/development/installation.rst
- docs/development/unit-tests.rst
- pyproject.toml
- requirements-dev.txt
> Replace `[dev]` optional dependencies with `requirements-dev.txt`

- .github/workflows/build.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- README.md
- docs/development/installation.rst
- docs/performance/benchmarks.rst
> Rename `master` to `main`

- .pre-commit-config.yaml
- docs/conf.py
- pyproject.toml
- requirements-dev.txt
- src/galois/_codes/_bch.py
- src/galois/_codes/_linear.py
- src/galois/_codes/_reed_solomon.py
- src/galois/_domains/_function.py
- src/galois/_domains/_linalg.py
- src/galois/_domains/_ufunc.py
- src/galois/_fields/_factory.py
- src/galois/_fields/_meta.py
- src/galois/_lfsr.py
- src/galois/_polys/_poly.py
- src/galois/_polys/_search.py
Also fixes bad `type[...]` annotation.
> Upgrade to Ruff 0.2.0

- .github/workflows/test.yaml
- src/galois/_domains/_calculate.py
- src/galois/_domains/_meta.py
- src/galois/_domains/_ufunc.py
- src/galois/_fields/_array.py
- src/galois/_fields/_gf2.py
- tests/fields/conftest.py
- tests/fields/test_arithmetic.py
> Allow `ufunc_mode="python-calculate"` for all fields

- src/galois/_domains/_linalg.py
Fixes #593, @rafaelha, @theodotk
Here's my abbreviated performance test. It would be nice to write a set of `.npy` files (with the result `C = A @ B`) before the change and compare them to after the change. I want to make sure no arithmetic is broken.
```python
import galois
dim1 = 10
for p in [2, 7, 1_009, 1_000_003]:
GF = galois.GF(p)
for dim2 in [10, 100, 1_000, 10_000, 100_000, 1_000_000]:
A = GF.Random((dim1, dim2))
B = GF.Random((dim2, dim1))
print(p, dim1, dim2)
%timeit A @ B
```
```
2 10 10
29.7 μs ± 718 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
2 10 100
37.1 μs ± 1.28 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
2 10 1000
90.3 μs ± 1.88 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
2 10 10000
599 μs ± 8.49 μs per loop (mean ± std. …
```
> Perform linear algebra using faster BLAS implementation, if possible

- src/galois/_fields/_array.py
- tests/fields/test_arithmetic.py
Change "if" else "elif".  Add tests for failing behavior.
> Fix Bug #599 and add a test.

- src/galois/_domains/_ufunc.py
- src/galois/_fields/_array.py
- src/galois/_fields/_meta.py
- src/galois/typing.py
- tests/fields/test_classes.py
> Make arithmetic `TypeError` more explicit
