README.md
docs/pages/basic_usage.rst
docs/pages/tutorials/constructing_fields.rst
docs/pages/tutorials/extremely_large_fields.rst
galois/gf.py
tests/fields/test_methods.py

```python
In [1]: import galois                                                                                                        
In [2]: GF = galois.GF_factory(2, 8)                                                                                         
In [3]: a = GF.Random(10)                                                                                                    
In [4]: print(a)                                                                                                                    
GF([143,   5,  38,   1, 228, 119, 175, 167, 212, 130], order=2^8)
In [6]: with GF.display("poly"): 
...:     print(a) 
...:                                                                                                                      
GF([x^7 + x^3 + x^2 + x + 1, x^2 + …
```

Make display() method a context manager

---

docs/pages/tutorials/3_field_arithmetic.rst

Currently it looks like this where `mathrm` is not evaluated:
[https://galois.readthedocs.io/en/stable/pages/tutorials/3_field_arithmetic.html](https://galois.readthedocs.io/en/stable/pages/tutorials/3_field_arithmetic.html)

Fix math representation

---

galois/field/meta.py
galois/field/meta_func.py
galois/field/meta_gf2.py
galois/field/meta_gf2m.py
galois/field/meta_gfp.py
galois/field/meta_gfpm.py
galois/field/meta_ufunc.py
galois/group/meta_func.py
galois/group/meta_ufunc_add.py
galois/group/meta_ufunc_mul.py
galois/meta.py
galois/meta_func.py
galois/meta_ufunc.py

Don't compile all ufuncs and JIT functions at class build time, but at first-use time.
This prevents users from paying a load penalty for ufuncs or functions they never use. For those ufuncs/functions they do use, there is a slight delay (~100 ms) in the first call to JIT compile and then subsequent calls are fast. Even if all ufuncs/functions are used, this distributes the compile/load time.
Before:
```python
In [1]: %time import galois
CPU times: user 1.71 s, sys: 688 ms, total: 2.4 s
Wall time: 1.25 s
In [2]: %time GF = galois.GF(2**8)
CPU times: user 935 ms, sys: 11.6 ms, total: 946 ms
Wall time: 953 ms
In [3]: a = GF.Random(10)
In [4]: b = GF.Random(10)
In [5]: %time a / b
CPU times: user 544 µs, sys: 123 µs, total: 667 µs
Wall time: 629 µs
Out[5]: GF([132, 116,  38, 245,  71,  63, …
```

Optimize load times with JIT on-demand

---

docs/pages/galois.rst
galois/factor.py
galois/math_.py
tests/test_math.py

This pull request solves the terribly slow class creation of large prime powers as reported in #117.
It was reported that creating the class `GF(p**2)` took 3 hours for `p = 2**61 - 1`, where all the time was spent prime factoring `p**2`. With this pull request, that is now very fast.
```python
In [1]: import galois                                                                                                  
In [2]: p = 2**61 - 1; p                                                                                                  
Out[2]: 2305843009213693951
In [3]: galois.prime_factors(p**2)                                                                                     
Out[3]: ([2305843009213693951], [2])
In [4]: %timeit galois.prime_factors(p**2) …
```

Efficient prime factoring of perfect powers

---

galois/field/factory.py
galois/field/factory_extension.py
galois/field/factory_prime.py
galois/field/oakley.py

1. Unify `verify_irreducible` and `verify_primitive` arguments to a single `verify` argument
2. Allow tuples, lists, or ndarrays for `irreducible_poly` and `primitive_element`
Point 2 allows this code
```python
GF = galois.GF(p**2, irreducible_poly=galois.Poly([1,0,1], field=galois.GF(p)), primitive_element=galois.Poly([1,6], field=galois.GF(p)))
```
to be abbreviated to
```python
GF = galois.GF(p**2, irreducible_poly=[1,0,1], primitive_element=[1,6])
```

Clean up `galois.GF` arguments

---

galois/_fields/_array.py
galois/_fields/_calculate.py
galois/_fields/_gfp.py
galois/_fields/_gfpm.py
galois/_fields/_lookup.py
galois/_fields/_properties.py

As noted in #192, the construction and verification overhead when `__new__()` is called for new `FieldArray` objects can be prohibitively expensive, such as with row reduction.
There are multiple contributors. This PR attempts to resolve them and document the performance impacts. The reference example is below:
```python
In [1]: import numpy as np
In [2]: import galois
In [3]: import cProfile
In [4]: GF = galois.GF(340282366762482138443322565580356624661)
In [5]: np.random.seed(123456789)
In [6]: X = GF.Random((20, 30))
In [7]: %timeit X.row_reduce()
747 ms ± 4.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [8]: cProfile.run("X.row_reduce()", sort="tottime")
2006758 function calls (1967138 primitive calls) in 1.124 seconds
Ordered by: internal time
ncalls  tottime  percall …
```

Make `FieldArray` construction more efficient

---

galois/_fields/_array.py
tests/fields/test_linalg.py

As pointed out in #202, currently `ndarray.dot()` isn't overridden / supported. This PR adds that.
Now `a.dot(b)` works the same as `np.dot(a, b)`.
```python
In [2]: import numpy as np
In [3]: a = galois.GF2.Random(4); a
Out[3]: GF([1, 1, 0, 0], order=2)
In [4]: b = galois.GF2.Random((4,4)); b
Out[4]: 
GF([[1, 0, 1, 1],
[1, 0, 1, 0],
[0, 1, 1, 1],
[0, 1, 1, 0]], order=2)
In [5]: np.dot(a, b)
Out[5]: GF([0, 0, 0, 1], order=2)
In [6]: a @ b
Out[6]: GF([0, 0, 0, 1], order=2)
In [7]: a.dot(b)
Out[7]: GF([0, 0, 0, 1], order=2)
```

Support `ndarray.dot()`

---

galois/_codes/_bch.py
galois/_codes/_cyclic.py
galois/_fields/_array.py
galois/_fields/_class.py
galois/_polys/_functions.py
tests/polys/test_minimal_polys.py

Fixes #205.
For `x**np.arange(a, b)`, the default dtype is `int`, which on most platforms is `np.int64`. If `x**b` is larger than `2**63`, the calculation will overflow and result in 0 or a negative value. This can be resolved by specifying `x**np.arange(a, b, dtype=GF.dtypes[-1])`, which uses the largest dtype for the given field.

Fix `np.arange()` exponentiation overflows

---

.github/workflows/test.yml
requirements-min.txt
setup.cfg

I believe this will require Numba 0.55, which isn't released as of 12/06/21. This PR is awaiting newer versions to re-test.
Update: This PR adds support for Python 3.10 and NumPy 1.21 through Numba 0.55.

Support Python 3.10

---

galois/_codes/_bch.py
galois/_codes/_reed_solomon.py
galois/_fields/_main.py
tests/fields/test_additive_order.py
tests/fields/test_field_norm.py
tests/fields/test_field_trace.py
tests/fields/test_multiplicative_order.py

```python
In [2]: GF = galois.GF(2**4)
In [3]: x = GF.Elements()
In [4]: x.additive_order()
Out[4]: array([1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
In [5]: x * x.additive_order()
Out[5]: GF([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], order=2^4)
```
```python
In [2]: GF = galois.GF(2**4)
In [3]: x = GF.Range(1, GF.order); x
Out[3]: 
GF([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
order=2^4)
In [4]: x.multiplicative_order()
Out[4]: array([ 1, 15, 15, 15, 15,  3,  3,  5, 15,  5, 15,  5, 15, 15,  5])
In [5]: x ** x.multiplicative_order()
Out[5]: GF([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], order=2^4)
```

Add additive and multiplicative order methods to `FieldArray`

---

galois/_prime.py
tests/test_primes.py

The functions now work as follows:
```python
In [2]: galois.prev_prime(10_000_000)
Out[2]: 9999991
In [3]: galois.prev_prime(10_000_000 + 1)
Out[3]: 9999991
In [4]: galois.next_prime(10_000_000)
Out[4]: 10000019
In [5]: galois.next_prime(10_000_019)
Out[5]: 10000079
```

Make `prev_prime()` and `next_prime()` without bound

---

galois/_fields/_main.py
tests/fields/test_quadratic_residues.py

```python
In [2]: GF = galois.GF(11)
In [3]: x = GF.Elements(); x
Out[3]: GF([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], order=11)
In [4]: x.is_quadratic_residue()
Out[4]: 
array([ True,  True, False,  True,  True,  True, False, False, False,
True, False])
In [5]: GF.quadratic_residues
Out[5]: GF([0, 1, 3, 4, 5, 9], order=11)
In [6]: GF.quadratic_non_residues
Out[6]: GF([ 2,  6,  7,  8, 10], order=11)
```

Add functions to test and return quadratic (non-)residues

---

README.md
docs/api/numpy-examples.rst
docs/basic-usage.rst
galois/_fields/_gf2m.py
galois/_fields/_gfp.py
galois/_fields/_gfpm.py
galois/_fields/_main.py
galois/_fields/_ufuncs.py
np/arithmetic.py
tests/fields/test_sqrt.py

```python
In [2]: import numpy as np
In [3]: GF = galois.GF(13)
In [4]: x = GF.quadratic_residues; x
Out[4]: GF([ 0,  1,  3,  4,  9, 10, 12], order=13)
In [5]: r = np.sqrt(x)
In [6]: r, -r
Out[6]: 
(GF([0, 1, 4, 2, 3, 6, 5], order=13),
GF([ 0, 12,  9, 11, 10,  7,  8], order=13))
In [7]: r**2
Out[7]: GF([ 0,  1,  3,  4,  9, 10, 12], order=13)
In [8]: (-r)**2
Out[8]: GF([ 0,  1,  3,  4,  9, 10, 12], order=13)
```

Support `np.sqrt()`

---

setup.cfg

fccdf0d686d0c8dfdf6d344220b28fe903d350ce accidentally instructed `pytest-cov` to exclude all source code lines. This PR fixes that. This also fixes codecov.io not working properly as discussed in #255.

Fix code coverage exclusion of typing overloads

---

README.md
docs/_static/extra.css
galois/_fields/_functions.py
galois/_fields/_gfp.py
galois/_fields/_gfpm.py
galois/_fields/_linalg.py
galois/_fields/_main.py
galois/_fields/_ufuncs.py
galois/_lfsr.py

This PR implements the proposal from #307. Performance benefits are seen. Here are some examples.
```python
In [2]: GF = galois.GF(2**8)
In [3]: x = GF.Random(10_000_000, seed=1); x
Out[3]: GF([255, 228,  34, ..., 146, 176, 223], order=2^8)
In [4]: y = GF.Random(10_000_000, seed=2); y
Out[4]: GF([193,  88, 107, ...,   1, 170,  95], order=2^8)
In [5]: x * y
Out[5]: GF([172,  42,  55, ..., 146,  33,  57], order=2^8)
In [7]: %timeit x * y
40.5 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [7]: %timeit x * y
33.8 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
```python
In [2]: GF = galois.GF(2**8)
In [3]: x = GF.Random(10_000_000, seed=1); x
Out[3]: GF([255, 228,  34, ..., 146, 176, 223], order=2^8)
In …
```

Internally avoid element verification cost of `.view(GF)`

---

galois/_fields/_main.py
requirements-dev.txt

```python
In [2]: GF = galois.GF(2**8)
```
```python
In [3]: %timeit GF([[1, 2], [3, 4], [5, 6]])
72.9 µs ± 280 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
In [3]: %timeit GF([[1, 2], [3, 4], [5, 6]])
21 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
```python
In [4]: %timeit GF([[1, 2], ["x + 1", 4], [5, "x^2 + x"]])
87.4 µs ± 203 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
In [4]: %timeit GF([[1, 2], ["x + 1", 4], [5, "x^2 + x"]])
45.7 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
```python
In [5]: %timeit GF(4)
21.1 µs ± 86.1 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
In [5]: %timeit GF(4)
2.85 µs ± 11.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops …
```

Speed-up array creation

---

galois/_fields/_functions.py
galois/_fields/_main.py
galois/_fields/_poly_functions.py
galois/_poly_conversion.py
scripts/sparse_poly_performance_test.py
tests/polys/test_arithmetic_implementations.py
tests/polys/test_conversions.py
tests/polys/test_operations.py

This PR implements #176. As a consequence of removing `DensePoly`, `BinaryPoly`, and `SparsePoly` and consolidating them into `Poly`, binary array arithmetic/creation is much faster. Below are some examples.
```python
In [2]: f = galois.Poly.Random(20, seed=1); f
Out[2]: Poly(x^20 + x^19 + x^16 + x^15 + x^13 + x^11 + x^9 + x^8 + x^7 + x^5 + x^4 + x^2 + 1, GF(2))
In [3]: g = galois.Poly.Random(10, seed=1); g
Out[3]: Poly(x^10 + x^9 + x^6 + x^5 + x^3 + x, GF(2))
In [4]: f * g
Out[4]: Poly(x^30 + x^28 + x^22 + x^20 + x^19 + x^13 + x^11 + x^10 + x^9 + x^8 + x^5 + x, GF(2))
```
```python
In [5]: %timeit f * g
196 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
In [5]: %timeit f * g
2.66 µs ± 13 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops …
```

Refactor `Poly` class and its inheritance

---

galois/_fields/_gf2m.py
galois/_fields/_gfp.py
galois/_fields/_gfpm.py
galois/_fields/_main.py
tests/fields/test_assignment.py

This PR cleans up element assignment and verification and removes the need to cast every ufunc input to an integer. Fixes #321
There is a small performance benefit, too.
```python
In [2]: GF = galois.GF(109987**4)
In [3]: x = GF.Random((1000), seed=1)
In [4]: y = GF.Random((1000), seed=2)
In [5]: x * y;
In [7]: %timeit x * y;
56.2 ms ± 174 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [6]: %timeit x * y;
55.3 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Ensure `dtype=object` arrays always have `int` objects, even after assignment

---

galois/_prime.py
tests/test_factor.py

Raise `RuntimeError` if an answer cannot be found, not return `None`

---

galois/_codes/_bch.py
galois/_codes/_cyclic.py
galois/_codes/_linear.py
galois/_codes/_reed_solomon.py
galois/_lfsr.py
galois/_ntt.py

For who knows what reason, Sphinx will sometimes **completely omit** a function/method signature if a type hint isn't forward referenced. These only apply to `galois` classes, it seems.
Because of this *silent error*, there were some missing signatures in the docs from the last release. This PR should add them back in.
Sphinx is a terribly frustrating tool........

Fix missing function signatures

---

galois/_polys/_poly.py
tests/polys/test_irreducible_polys.py

Fixes #360. In certain circumstances a `np.int64` was returned from `Poly.degree`. When performing irreducibility checks and computing `q**m`, if either `q` or `m` wasn't an `int` the arithmetic could overflow and the irreducibility check became erroneous.
Now, #360 runs as follows:
```python
import galois
f = galois.Poly.Degrees([233, 74, 0])
print(galois.is_irreducible(f))
#initial detection loop
for k in range(1, 233):
poly = galois.Poly.Degrees([233, k, 0])
if galois.is_irreducible(poly):
print("Found one: ", k, poly)
```
```python
In [1]: %run test_2.py
True
Found one:  74 x^233 + x^74 + 1
Found one:  159 x^233 + x^159 + 1
In [2]: 
```

Always return `int` from `Poly.degree`

---

setup.cfg

Add support for numpy 1.22

---

README.md

Released yesterday: https://github.blog/2022-05-19-math-support-in-markdown/

Use mathjax in GitHub-flavored markdown

---

galois/_domains/_calculate.py
galois/_domains/_meta.py
galois/_domains/_ufunc.py
galois/_fields/_ufunc.py
tests/fields/test_arithmetic.py

The Pollard-rho discrete logarithm algorithm is only applicable to multiplicative groups with prime order. That ends up being only some `GF(2^m)` fields. There is a large performance bump, though. 🚀 
```python
In [2]: GF = galois.GF(2**19, compile="jit-calculate")
In [3]: GF._log
Out[3]: <galois._domains._calculate.log_brute_force at 0x7fc1419f7430>
In [4]: x = GF.Random(100, low=1, seed=1)
In [5]: x.log();
In [6]: %timeit x.log()
82.2 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
```python
In [2]: GF = galois.GF(2**19, compile="jit-calculate")
In [3]: GF._log
Out[3]: <galois._domains._calculate.log_pollard_rho at 0x7fdba7d8a2e0>
In [4]: x = GF.Random(100, low=1, seed=1)
In [5]: x.log();
In [6]: %timeit x.log()
4.63 ms ± …
```

Pollard-rho discrete logarithm

---

galois/_domains/_array.py
galois/_domains/_calculate.py
galois/_domains/_lookup.py
galois/_domains/_ufunc.py
galois/_fields/_array.py
galois/_fields/_ufunc.py
tests/fields/test_arithmetic.py

The Pohlig-Hellman discrete logarithm is more efficient than brute force, but is the most efficient when `n = p^m - 1` is smooth.
```python
In [2]: GF = galois.GF(491954233)
In [3]: GF._log
Out[3]: <galois._domains._calculate.log_brute_force at 0x7f2b76ece700>
In [4]: x = GF.Random(low=1, seed=1)
In [5]: x.log()
Out[5]: 478161536
In [6]: %timeit x.log()
1.83 s ± 2.26 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
```python
In [2]: GF = galois.GF(491954233)
In [3]: GF._log
Out[3]: <galois._domains._calculate.log_pohlig_hellman at 0x7f033d088ac0>
In [4]: galois.factors(GF.order - 1)
Out[4]: ([2, 3, 7, 11, 19, 14011], [3, 1, 1, 1, 1, 1])
In [5]: x = GF.Random(low=1, seed=1)
In [6]: x.log()
Out[6]: 478161536
In [7]: %timeit x.log()
47.8 …
```

Pohlig-Hellman discrete logarithm

---

README.md
docs/basic-usage/array-arithmetic.rst
docs/basic-usage/array-creation.rst
galois/_domains/_calculate.py
galois/_domains/_ufunc.py
galois/_fields/_array.py
galois/typing.py
tests/fields/test_squares.py

```python
In [2]: GF = galois.GF(13)
In [3]: GF.squares
Out[3]: GF([ 0,  1,  3,  4,  9, 10, 12], order=13)
In [4]: GF.non_squares
Out[4]: GF([ 2,  5,  6,  7,  8, 11], order=13)
In [5]: import numpy as np
In [6]: np.sqrt(GF.squares)
Out[6]: GF([0, 1, 4, 2, 3, 6, 5], order=13)
```

Use "square" terminology instead of "quadratic residue"

---

docs/requirements.txt
galois/_fields/_array.py
galois/_fields/_factory.py
tests/fields/test_classes.py

Fixes #388
```python
In [1]: import pickle
In [2]: import galois
In [3]: GF = galois.GF(47)
In [4]: print(GF.properties)
Galois Field:
name: GF(47)
characteristic: 47
degree: 1
order: 47
irreducible_poly: x + 42
is_primitive_poly: True
primitive_element: 5
In [5]: with open("gf_class.pkl", "wb") as f:
...:     pickle.dump(GF, f)
...: 
In [6]: with open("gf_class.pkl", "rb") as f:
...:     GF_loaded = pickle.load(f)
...:
In [7]: print(GF_loaded.properties)
Galois Field:
name: GF(47)
characteristic: 47
degree: 1
order: 47
irreducible_poly: x + 42
is_primitive_poly: True
primitive_element: 5
```
```python
In [1]: import pickle
In [2]: import galois
In [3]: GF = galois.GF(47)
In [4]: x = GF.Random(10, low=1, seed=1); x
Out[4]: GF([46, 41,  7, 22, 44, 34, 24, 19, 31, 15], order=47)
In [5]: …
```

Support pickling `FieldArray` subclasses and instances

---

.github/workflows/build.yaml
.github/workflows/docs.yaml
.github/workflows/release.yaml
.readthedocs.yml
README.md
docs/development/documentation.rst
docs/index.rst
docs/release-notes/v0.0.33.md
docs/requirements.txt
pyproject.toml

Fix package structure from last attempted TestPyPI upload.
```
Run pypa/gh-action-pypi-publish@v1.4.2
/usr/bin/docker run --name da4232d721ca440f8ab4e6b2f53633fd_b51a0f --label 229416 --workdir /github/workspace --rm -e "INPUT_USER" -e "INPUT_PASSWORD" -e "INPUT_REPOSITORY_URL" -e "INPUT_PACKAGES_DIR" -e "INPUT_VERBOSE" -e "INPUT_VERIFY_METADATA" -e "INPUT_SKIP_EXISTING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" …
```

Fix packaging of direct dependencies

---

.github/workflows/test.yaml
pyproject.toml
tests/fields/test_factory.py

Using `pytest-xdist` speeds up the unit testing by roughly a factor of 2.

Use `pytest-xdist`

---

docs/basic-usage/array-arithmetic.rst
docs/basic-usage/element-representation.rst
docs/basic-usage/poly-arithmetic.rst
docs/requirements.txt

Fix `<details>` sections in docs

---

docs/basic-usage/array-arithmetic.rst
docs/basic-usage/array-classes.rst
docs/basic-usage/array-creation.rst
docs/basic-usage/element-representation.rst
docs/basic-usage/poly-arithmetic.rst
docs/basic-usage/poly.rst
docs/conf.py
docs/ipython_with_reprs.py
docs/tutorials/intro-to-extension-fields.rst
docs/tutorials/intro-to-prime-fields.rst
src/galois/_fields/_array.py
src/galois/_fields/_meta.py
src/galois/typing.py

Adds a custom Sphinx directive `ipython-with-reprs` to simplify a common pattern in the `galois` documentation where an example is performed in each element representation in separate tabs.
```rst
.. md-tab-set::
.. md-tab-item:: Integer
.. ipython:: python
GF9 = galois.GF(3**2)
print(GF9.properties)
.. md-tab-item:: Polynomial
.. ipython:: python
GF9 = galois.GF(3**2, display="poly")
print(GF9.properties)
.. md-tab-item:: Power
.. ipython:: python
GF9 = galois.GF(3**2, display="power")
print(GF9.properties)
```
```rst
.. ipython-with-reprs:: int,poly,power
:name: GF9
GF9 = galois.GF(3**2)
print(GF9.properties)
```

Add `ipython-with-reprs` Sphinx directive

---

src/galois/_domains/_function.py
src/galois/_domains/_linalg.py
src/galois/_polys/_dense.py

Improves performance for #439.
```python
In [2]: GF = galois.GF(2**16, compile="jit-calculate")
In [3]: A = GF.Random((500, 500), seed=1)
In [4]: A = GF.Random((300, 400), seed=1)
In [5]: B = GF.Random((400, 500), seed=2)
In [6]: %timeit A @ B
1.49 s ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [7]: %timeit A @ B
152 ms ± 732 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
```python
In [2]: GF = galois.GF(2**16, compile="jit-calculate")
In [3]: f = galois.Poly.Random(100, seed=1, field=GF)
In [4]: x = GF.Random(100_000, seed=1)
In [6]: %timeit f(x)
220 ms ± 745 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [6]: %timeit f(x)
31.3 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Parallelize JIT functions

---

src/galois/_prime.py

There is a small bug in factorization function when it gets to factors above 10M and starts calling `pollard_rho`. If it can't find a factor using `f(x)=x^2+c (mod n)`  with `c==1` it is supposed to update `c` to some other random value. But initialization accidentally got in the loop body and would always reset `c` back to `1`.
Since `pollard_rho` is only called to get factors larger than 10M at the point, and the fact that `c=1` usually works it is quite rare for this bug to surface, but in the rare case when `c=1` doesn't work it causes the infinite loop. Example would be `galois.GF(2400610585866217)` which requires factorization of `2400610585866217 - 1 = 2^3 * 3 * 100025441077759 = 2^3 * 3 * 10000537 * 10002007`.

Fix a bug in factorization function causing infinite loops in rare cases

---

src/galois/_polys/_irreducible.py
src/galois/_polys/_poly.py
src/galois/_polys/_primitive.py
tests/polys/test_irreducible_polys.py
tests/polys/test_primitive_polys.py

Implements #458.
```python
In [2]: galois.irreducible_poly(7, 3)
Out[2]: Poly(x^3 + 2, GF(7))
In [3]: galois.irreducible_poly(7, 3, terms=3)
Out[3]: Poly(x^3 + x + 1, GF(7))
In [4]: galois.primitive_poly(7, 3)
Out[4]: Poly(x^3 + 3x + 2, GF(7))
In [5]: galois.primitive_poly(7, 3, terms=4)
Out[5]: Poly(x^3 + x^2 + x + 2, GF(7))
```
```python
In [2]: list(galois.primitive_polys(3, 5))
Out[2]: 
[Poly(x^5 + 2x + 1, GF(3)),
Poly(x^5 + 2x^2 + x + 1, GF(3)),       
Poly(x^5 + x^3 + x + 1, GF(3)),        
Poly(x^5 + x^3 + 2x^2 + 1, GF(3)),     
Poly(x^5 + x^3 + 2x^2 + 2x + 1, GF(3)),
Poly(x^5 + 2x^3 + x^2 + 1, GF(3)),     
Poly(x^5 + 2x^3 + 2x^2 + x + 1, GF(3)),
Poly(x^5 + x^4 + 2x + 1, GF(3)),
Poly(x^5 + x^4 + x^2 + 1, GF(3)),
Poly(x^5 + x^4 + x^2 + x + …
```

Add `terms` kwarg to irreducible and primitive poly functions

---

README.md
docs/_templates/base.html
src/galois/_domains/_linalg.py
tests/fields/test_linalg.py

Fixes #476.
```python
import numpy as np
import galois
GF = galois.GF(2)
A = GF(
[
[1, 0, 0, 0, 0, 1],
[1, 1, 1, 1, 0, 1],
[1, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0],
[0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 1],
]
)
print(f"A = \n{A}")
P, L, U = A.plu_decompose()
print(f"P = \n{P}")
print(f"L = \n{L}")
print(f"U = \n{U}")
PLU = P @ L @ U
print(f"PLU = \n{PLU}")
print(np.array_equal(A, PLU))
```
```console
$ python3 bug_476.py
A = 
[[1 0 0 0 0 1]
[1 1 1 1 0 1]
[1 0 0 0 0 0]
[0 1 0 0 0 0]
[0 0 1 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 1 0]
[0 0 0 0 0 1]]
P = 
[[1 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
[0 0 1 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]]
L = 
[[1 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0]
[0 1 1 0 0 0 0 0]
[0 0 1 1 …
```

Fix array sizing in PLU decomposition

---

pyproject.toml

Comply with PEP 561

---

src/galois/_codes/_bch.py
src/galois/_codes/_reed_solomon.py
src/galois/_domains/_function.py
tests/codes/test_bch.py

Fix BCH/RS decoder caching bug

---

src/galois/_polys/_dense.py

Fix polynomial power overflow bug

---

tests/fields/conftest.py

Related to #491.
Not sure if this affects older supported versions, and it's also not that easy for me to check locally, so let's see with the Github CI.

Removes deprecation warnings from numpy 1.25

---

src/galois/_domains/_array.py

Appease `mypy` for arithmetic

---

src/galois/_prime.py
tests/test_primes.py

Also, it fixes the bug of skipping the first two numbers after n. For example, in the previous version:
>>> galois.next_prime(100000034)
100000037
>>> galois.next_prime(100000035)
100000039
>>> galois.next_prime(100000036)
100000039
>>> galois.next_prime(100000037)
100000049

Implementation of wheel factorization

---

src/galois/_helper.py

This PR addresses https://github.com/mhostetter/galois/issues/544
I confirmed that I ran into the issue by running tests w/ `python -OO -m pytest tests/`. The issue is resolved & all tests completed after this update.
Let me know if there are any version or release notes I should be handling in this PR. I could not find any guidelines on this for developers in the repository's documentation.

Check for and handle None docstrings

---

pyproject.toml
src/galois/_domains/_function.py
src/galois/_domains/_ufunc.py
src/galois/_fields/_array.py
src/galois/_polys/_dense.py

Probably should merge into `release/0.4.x`.

Support NumPy 2.0

---

src/galois/_databases/_interface.py

https://github.com/mhostetter/galois/issues/555
I changed three things:
(1) as before, check_same_thread=False to sqlite3.connect
(2) used a lock for cursor actions to prevent the situation where a query is made before the result for another query is read
(3) used the same lock for instance creation, since two threads could race and create two connections (which is unintended).
An alternative approach is to somehow create a connection per thread, then the locks won't be necessary
This approach sadly introduces an import from `threading`. I hope it is ok, this module should be present in all supported interpreters.

Add multithreading compatibility

---

src/galois/_domains/_linalg.py

This is a follow up to #596 
The reason that no speedup was observed [here](https://github.com/mhostetter/galois/pull/596#issuecomment-2798902141) is the small outer dimension `dim1=10`. Here, `c` is just a 10 x 10 matrix, so the modulo operation is negligible compared to inner index contraction.
When the outer dimensions are similar or large compared to the inner dimensions, the modulo operation can be time intensive. And here, integer conversion definitely saves time:
```python
import numpy as np
a_int = np.random.randint(0, 2**9, (2000, 4000))
a_float = a_int.astype(np.float64)
%timeit a_int % 2  # 12.1 ms ± 576 μs per loop
%timeit a_float % 2  # 196 ms ± 7.13 ms per loop
```
A benchmark script:
```python
import galois
dim1 = 1000
for p in [1_009,]:
GF = galois.GF(p)
for dim2 in [10, …
```

Convert to int for faster mod
